[build]
  publish = "/"
  command = ""

[dev]
  framework = "vite"
  targetPort = 3000
  port = 8888

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[[redirects]]
  from = "/send-otp"
  to = "/.netlify/functions/send-otp"
  status = 200
  force = true

[[redirects]]
  from = "/verify-otp"
  to = "/.netlify/functions/verify-otp"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/forms.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
